spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret_key: ${SECRET_KEY}
  access_token_exp: ${ACCESS_EXP}

service:
  url: ${SERVICE_URL}
  key: ${SERVICE_KEY}